[package]
name = "canoa"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4", default-features = false, features = ["macros"]}

[profile.release]
strip = true
lto = true
codegen-units = 1
